name: Notify Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print notification message
        run: |
          echo "Novo Pull Request aberto ou atualizado!"
          echo "Autor da alteração: ${{ github.actor }}"
          echo "Por favor, verifique a revisão pendente."
